services:
  base: &base
    image: chatwoot/chatwoot:v4.13.0
    env_file: .env
    volumes:
      - storage_data:/app/storage
      - ./favicons/favicon-16x16.png:/app/public/favicon-16x16.png:ro
      - ./favicons/favicon-16x16.png:/app/public/packs/favicon-16x16.png:ro
      - ./favicons/favicon-badge-16x16.png:/app/public/favicon-badge-16x16.png:ro
      - ./favicons/favicon-badge-16x16.png:/app/public/packs/favicon-badge-16x16.png:ro
      - ./favicons/favicon-32x32.png:/app/public/favicon-32x32.png:ro
      - ./favicons/favicon-32x32.png:/app/public/packs/favicon-32x32.png:ro
      - ./favicons/favicon-badge-32x32.png:/app/public/favicon-badge-32x32.png:ro
      - ./favicons/favicon-badge-32x32.png:/app/public/packs/favicon-badge-32x32.png:ro
      - ./favicons/favicon-96x96.png:/app/public/favicon-96x96.png:ro
      - ./favicons/favicon-96x96.png:/app/public/packs/favicon-96x96.png:ro
      - ./favicons/favicon-badge-96x96.png:/app/public/favicon-badge-96x96.png:ro
      - ./favicons/favicon-badge-96x96.png:/app/public/packs/favicon-badge-96x96.png:ro
      - ./favicons/favicon-512x512.png:/app/public/favicon-512x512.png:ro
      - ./favicons/favicon-512x512.png:/app/public/packs/favicon-512x512.png:ro
      - ./favicons/favicon-badge-512x512.png:/app/public/favicon-badge-512x512.png:ro
      - ./favicons/favicon-badge-512x512.png:/app/public/packs/favicon-badge-512x512.png:ro
    networks:
      - default
      - villanova-net

  rails:
    <<: *base
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=villanova-net
      - traefik.http.routers.chatwoot.rule=Host(`multi-chat.villanovacondominios.com.br`)
      - traefik.http.routers.chatwoot.entrypoints=websecure
      - traefik.http.routers.chatwoot.tls.certresolver=le
      - traefik.http.services.chatwoot.loadbalancer.server.port=3000

  sidekiq:
    <<: *base
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  storage_data:
  postgres_data:
  redis_data:

networks:
  villanova-net:
    external: true
